# Build directories
**/build
**/target
**/generated

# Generated CMake files
**/CMakeCache.txt
**/CMakeFiles
**/cmake_install.cmake

# IDE files
**/.vscode/

# Git
.git
.gitignore

# Docker
Dockerfile*
simtest
