// Code generated by MockGen. DO NOT EDIT.
// Source: source.quilibrium.com/quilibrium/monorepo/protobufs (interfaces: GlobalServiceClient)
//
// Generated by this command:
//
//	mockgen -destination=global_service_mock.go -package=mocks source.quilibrium.com/quilibrium/monorepo/protobufs GlobalServiceClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
	protobufs "source.quilibrium.com/quilibrium/monorepo/protobufs"
)

// MockGlobalServiceClient is a mock of GlobalServiceClient interface.
type MockGlobalServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockGlobalServiceClientMockRecorder
	isgomock struct{}
}

// MockGlobalServiceClientMockRecorder is the mock recorder for MockGlobalServiceClient.
type MockGlobalServiceClientMockRecorder struct {
	mock *MockGlobalServiceClient
}

// NewMockGlobalServiceClient creates a new mock instance.
func NewMockGlobalServiceClient(ctrl *gomock.Controller) *MockGlobalServiceClient {
	mock := &MockGlobalServiceClient{ctrl: ctrl}
	mock.recorder = &MockGlobalServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGlobalServiceClient) EXPECT() *MockGlobalServiceClientMockRecorder {
	return m.recorder
}

// GetAppShards mocks base method.
func (m *MockGlobalServiceClient) GetAppShards(ctx context.Context, in *protobufs.GetAppShardsRequest, opts ...grpc.CallOption) (*protobufs.GetAppShardsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAppShards", varargs...)
	ret0, _ := ret[0].(*protobufs.GetAppShardsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppShards indicates an expected call of GetAppShards.
func (mr *MockGlobalServiceClientMockRecorder) GetAppShards(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppShards", reflect.TypeOf((*MockGlobalServiceClient)(nil).GetAppShards), varargs...)
}

// GetGlobalFrame mocks base method.
func (m *MockGlobalServiceClient) GetGlobalFrame(ctx context.Context, in *protobufs.GetGlobalFrameRequest, opts ...grpc.CallOption) (*protobufs.GlobalFrameResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetGlobalFrame", varargs...)
	ret0, _ := ret[0].(*protobufs.GlobalFrameResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGlobalFrame indicates an expected call of GetGlobalFrame.
func (mr *MockGlobalServiceClientMockRecorder) GetGlobalFrame(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGlobalFrame", reflect.TypeOf((*MockGlobalServiceClient)(nil).GetGlobalFrame), varargs...)
}

// GetGlobalProposal mocks base method.
func (m *MockGlobalServiceClient) GetGlobalProposal(ctx context.Context, in *protobufs.GetGlobalProposalRequest, opts ...grpc.CallOption) (*protobufs.GlobalProposalResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetGlobalProposal", varargs...)
	ret0, _ := ret[0].(*protobufs.GlobalProposalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGlobalProposal indicates an expected call of GetGlobalProposal.
func (mr *MockGlobalServiceClientMockRecorder) GetGlobalProposal(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGlobalProposal", reflect.TypeOf((*MockGlobalServiceClient)(nil).GetGlobalProposal), varargs...)
}

// GetGlobalShards mocks base method.
func (m *MockGlobalServiceClient) GetGlobalShards(ctx context.Context, in *protobufs.GetGlobalShardsRequest, opts ...grpc.CallOption) (*protobufs.GetGlobalShardsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetGlobalShards", varargs...)
	ret0, _ := ret[0].(*protobufs.GetGlobalShardsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGlobalShards indicates an expected call of GetGlobalShards.
func (mr *MockGlobalServiceClientMockRecorder) GetGlobalShards(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGlobalShards", reflect.TypeOf((*MockGlobalServiceClient)(nil).GetGlobalShards), varargs...)
}

// GetLockedAddresses mocks base method.
func (m *MockGlobalServiceClient) GetLockedAddresses(ctx context.Context, in *protobufs.GetLockedAddressesRequest, opts ...grpc.CallOption) (*protobufs.GetLockedAddressesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetLockedAddresses", varargs...)
	ret0, _ := ret[0].(*protobufs.GetLockedAddressesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLockedAddresses indicates an expected call of GetLockedAddresses.
func (mr *MockGlobalServiceClientMockRecorder) GetLockedAddresses(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLockedAddresses", reflect.TypeOf((*MockGlobalServiceClient)(nil).GetLockedAddresses), varargs...)
}

// GetWorkerInfo mocks base method.
func (m *MockGlobalServiceClient) GetWorkerInfo(ctx context.Context, in *protobufs.GlobalGetWorkerInfoRequest, opts ...grpc.CallOption) (*protobufs.GlobalGetWorkerInfoResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetWorkerInfo", varargs...)
	ret0, _ := ret[0].(*protobufs.GlobalGetWorkerInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkerInfo indicates an expected call of GetWorkerInfo.
func (mr *MockGlobalServiceClientMockRecorder) GetWorkerInfo(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkerInfo", reflect.TypeOf((*MockGlobalServiceClient)(nil).GetWorkerInfo), varargs...)
}
